
-- board.mv.db 를 접속하여 테이블 초기화
DROP TABLE IF EXISTS TB_BOARD;
CREATE TABLE TB_BOARD (
  IDX INT AUTO_INCREMENT PRIMARY KEY
  ,TITLE VARCHAR(250) NOT NULL
  ,CONTENT VARCHAR(1000) NOT NULL
  ,REG_NAME VARCHAR(250) NOT NULL
  ,REG_DATE DATE NOT NULL
  ,MOD_DATE DATE NULL
);

-- score.mv.db 를 접속하여 테이블 초기화
DROP TABLE IF EXISTS TB_SCORE;
CREATE TABLE TB_SCORE (
  IDX INT AUTO_INCREMENT PRIMARY KEY
  ,NAME VARCHAR(250) NOT NULL
  ,SCORE NUMERIC(20, 2) NOT NULL
);
