log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

# \uC804\uCCB4 SQL\uBB38 \uC81C\uD55C\uC5C6\uC774 \uCD9C\uB825
log4jdbc.dump.sql.maxlinelength=0
log4jdbc.auto.load.popular.drivers=false
log4jdbc.drivers=com.mysql.cj.jdbc.Driver

#MySQL\uAC19\uC740 \uACBD\uC6B0 log4jdbc\uAC00 \uAE30\uBCF8\uC73C\uB85C com.mysql.jdbc.Driver\uB97C \uC0AC\uC6A9\uD558\uC5EC \uC704\uC5D0 \uC124\uC815\uC744 \uCD94\uAC00\uD558\uC9C0 \uC54A\uC73C\uBA74 \uC544\uB798\uC640 \uAC19\uC740 \uB85C\uADF8\uAC00 \uCC0D\uD788\uAC8C \uB41C\uB2E4.
#Loading class 'com.mysql.jdbc.Driver'. This is deprecated. The new driver class is 'com.mysql.cj.jdbc.Driver'.
#log4jdbc.drivers=com.mysql.cj.jdbc.Driver
#log4jdbc.auto.load.popular.drivers=false